[package]
name = "paiagram-oudia-macros"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0.3", features = ["full"] }
