[package]
name = "paiagram-extensions"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
log.workspace = true
paiagram-core.workspace = true
parking_lot.workspace = true
rayon.workspace = true
rquickjs.workspace = true
wasmi.workspace = true

[dev-dependencies]
env_logger.workspace = true
