// SPDX-License-Identifier: MPL-2.0

use std::cell::RefCell;

use ecow::EcoVec;
use serde::{Deserialize, Serialize};

use crate::time::{Duration, TTime};
use crate::{IntervalCollection, StationKey, WorldGraph};

/// Travel mode. Travel mode defines how the vehicle travels.
#[derive(Clone, Serialize, Deserialize, Copy, Debug, PartialEq)]
pub enum TravelMode {
    At(TTime),
    For(Duration),
    Flexible,
}

#[derive(Clone, Serialize, Deserialize, Copy, Debug, PartialEq)]
pub struct TEntryId(u32);

/// An entry in the schedule. `TEntry` is short for `TimetableEntry`.
///
/// The schedule conatins an ordered list of entries. There are two categories for an entry:
/// `derived`, which is automatically generated by the system and may be invalidated, and `pinned`,
/// which can be only generated by sending explicit [`crate::Command`]s.
///
/// `derived` and `pinned` entries have different semantics. A derived entry may or may not visit
/// the station, while a pinned entry must visit the station. Each pinned entry has an ID.
#[derive(Clone, Serialize, Deserialize, Copy, Debug, PartialEq)]
pub enum TEntry {
    /// A derived state. this is calculated by the system.
    Derived { stn: StationKey, id: TEntryId },
    /// A pinned station. The trip must visit this station.
    /// This requires runtime checks to make sure that the start and end are valid.
    Pinned {
        stn: StationKey,
        trk: u16,
        arr: TravelMode,
        dep: TravelMode,
        id: TEntryId,
        external: bool,
    },
    /// A pinned station. The trip must visit this station,
    /// but the vehicle does not stop at the station.
    PinnedNonStop {
        stn: StationKey,
        trk: u16,
        pass: TravelMode,
        id: TEntryId,
        external: bool,
    },
}

#[derive(Clone, Serialize, Deserialize, PartialEq, Debug)]
pub struct TripSchedule {
    entries: EcoVec<TEntry>,
}

impl TripSchedule {
    pub fn new(entries: EcoVec<TEntry>) -> Self {
        Self { entries }
    }
}

#[derive(Clone, Copy)]
struct TEstimate {
    arr: TTime,
    dep: TTime,
}

impl TEstimate {
    fn duration(self) -> Duration {
        self.dep - self.arr
    }
}

struct EstimateSketch {
    stn: StationKey,
    slot: usize,
    dur: Duration,
}

thread_local! {
    static ESTIMATE_BUFFER: RefCell<Vec<EstimateSketch>> = RefCell::new(Vec::with_capacity(100));
    static OUTPUT_BUFFER: RefCell<Vec<(Option<TEstimate>, TEntry)>> = RefCell::new(Vec::with_capacity(100));
}

enum StackElem {
    Ignored,
    In(StationKey, Duration),
    AtAt(StationKey, TTime, TTime),
    ForAt(StationKey, Duration, TTime),
    ForFor(StationKey, Duration, Duration),
}

impl TripSchedule {
    fn estimates<F, R>(&self, intervals: &IntervalCollection, map: &WorldGraph, mut f: F) -> R
    where
        F: FnMut(&[(Option<TEstimate>, TEntry)]) -> R,
    {
        ESTIMATE_BUFFER.with(|r| {
            let mut estimate_buf = r.borrow_mut();
            estimate_buf.clear();
            OUTPUT_BUFFER.with(|r| {
                let mut output_buf = r.borrow_mut();
                output_buf.clear();
                for entry in &self.entries {
                    let se = make_se(*entry);
                    match se {
                        StackElem::Ignored => {
                            output_buf.push((None, *entry));
                        }
                        StackElem::In(stn, dur) => {
                            let es = EstimateSketch {
                                stn,
                                slot: estimate_buf.len(),
                                dur,
                            };
                            estimate_buf.push(es);
                        }
                        // unwind
                        StackElem::AtAt(stn, at, dt) => {}
                        StackElem::ForAt(stn, ad, dt) => {}
                        StackElem::ForFor(stn, ad, dd) => {}
                    };
                }
                // finalize
                f(output_buf.as_slice())
            })
        })
    }
}

fn make_se(entry: TEntry) -> StackElem {
    use StackElem as Se;
    use TravelMode as Tm;
    match entry {
        TEntry::Derived { stn, .. } => Se::In(stn, Duration::ZERO),
        TEntry::Pinned { external, .. } if external => Se::Ignored,
        TEntry::PinnedNonStop { external, .. } if external => Se::Ignored,
        TEntry::Pinned { stn, arr, dep, .. } => match (arr, dep) {
            (Tm::At(at), Tm::At(dt)) => Se::AtAt(stn, at, dt),
            (Tm::At(at), Tm::For(dd)) => Se::AtAt(stn, at, at + dd),
            (Tm::At(at), Tm::Flexible) => Se::AtAt(stn, at, at),
            (Tm::For(ad), Tm::At(dt)) => Se::ForAt(stn, ad, dt),
            (Tm::For(ad), Tm::For(dd)) => Se::ForFor(stn, ad, dd),
            (Tm::For(ad), Tm::Flexible) => Se::ForFor(stn, ad, Duration::ZERO),
            (Tm::Flexible, Tm::At(dt)) => Se::AtAt(stn, dt, dt),
            (Tm::Flexible, Tm::For(dd)) => Se::In(stn, dd),
            (Tm::Flexible, Tm::Flexible) => Se::In(stn, Duration::ZERO),
        },
        TEntry::PinnedNonStop { stn, .. } => Se::In(stn, Duration::ZERO),
    }
}
