use std::f32::consts::FRAC_PI_4;

use egui::*;
use itertools::{Itertools, chain};
use paiagram_core::route::{DiagramCache, StationRecord};
use paiagram_core::time::{Tick, TimetableTime};
use paiagram_core::trip::TEstimate;
use paiagram_core::{CanvasLength, RouteKey, TripKey};
use paiagram_export::GraphyFormat;
use paiagram_rw::ExportObject;
use serde::{Deserialize, Serialize};

pub(crate) mod gpu_draw;
// generated by build.rs
mod gpu_trip {
    include!(concat!(env!("OUT_DIR"), "/gpu_trip.rs"));
}
mod label_placement;

use super::{Navigatable, Tab};
use crate::App;
use crate::selection::{SelectedItem, SelectedItems};
use crate::tabs::diagram::label_placement::label_placement;

#[derive(Clone, Serialize, Deserialize)]
#[serde(into = "DiagramTabNoCache", from = "DiagramTabNoCache")]
pub(crate) struct DiagramTab {
    key: RouteKey,
    navi: DiagramTabNavigation,
    cache: DiagramCache,
    callback: gpu_draw::DiagramCallback,
}

/// [`DiagramTab`] w/o cache for serde
#[derive(Clone, Serialize, Deserialize)]
struct DiagramTabNoCache {
    key: RouteKey,
    navi: DiagramTabNavigation,
}

impl From<DiagramTab> for DiagramTabNoCache {
    fn from(DiagramTab { key, navi, .. }: DiagramTab) -> Self {
        Self { key, navi }
    }
}

impl From<DiagramTabNoCache> for DiagramTab {
    fn from(DiagramTabNoCache { key, navi }: DiagramTabNoCache) -> Self {
        Self {
            key,
            navi,
            cache: DiagramCache::default(),
            callback: gpu_draw::DiagramCallback::new(key),
        }
    }
}

impl DiagramTab {
    pub fn new(key: RouteKey) -> Self {
        Self {
            key,
            navi: DiagramTabNavigation::default(),
            cache: DiagramCache::default(),
            callback: gpu_draw::DiagramCallback::new(key),
        }
    }
}

impl PartialEq for DiagramTab {
    fn eq(&self, other: &Self) -> bool {
        self.key == other.key
    }
}

#[derive(Clone, Serialize, Deserialize)]
struct DiagramTabNavigation {
    x_offset: Tick,
    y_offset: CanvasLength,
    zoom: Vec2,
    #[serde(skip, default = "default_visible_rect")]
    visible_rect: Rect,
    max_height: CanvasLength,
}

impl Default for DiagramTabNavigation {
    fn default() -> Self {
        // Default horizontal scale: five minutes of time span one centimetre of canvas.
        let five_minutes_in_ticks = TimetableTime::from_hms(0, 5, 0).to_ticks().0 as f32;
        let one_cm_in_pts = CanvasLength::from_cm(1.0).to_egui_pts();
        Self {
            x_offset: Tick(0),
            y_offset: CanvasLength(0.0),
            zoom: vec2(one_cm_in_pts / five_minutes_in_ticks, 1.0),
            visible_rect: Rect::NOTHING,
            max_height: CanvasLength(0.0),
        }
    }
}

fn default_visible_rect() -> Rect {
    Rect::NOTHING
}

impl Navigatable for DiagramTabNavigation {
    type XOffset = Tick;
    type YOffset = CanvasLength;

    fn zoom_x(&self) -> f32 {
        self.zoom.x
    }
    fn zoom_y(&self) -> f32 {
        self.zoom.y * CanvasLength::egui_pts_per_mm() as f32
    }
    fn set_zoom(&mut self, zoom_x: f32, zoom_y: f32) {
        self.zoom = Vec2::new(zoom_x, zoom_y / CanvasLength::egui_pts_per_mm() as f32);
    }
    fn offset_x(&self) -> f64 {
        self.x_offset.0 as f64
    }
    fn offset_y(&self) -> f64 {
        self.y_offset.0
    }
    fn set_offset(&mut self, offset_x: f64, offset_y: f64) {
        self.x_offset = Tick(offset_x.round() as i64);
        self.y_offset = CanvasLength(offset_y);
    }
    fn visible_rect(&self) -> egui::Rect {
        self.visible_rect
    }
    fn allow_axis_zoom(&self) -> bool {
        true
    }
    fn clamp_zoom(&self, zoom_x: f32, zoom_y: f32) -> (f32, f32) {
        let ppmm = CanvasLength::egui_pts_per_mm() as f32;
        (
            zoom_x.clamp(0.00005, 0.4),
            zoom_y.clamp(ppmm * 0.1, ppmm * 2048.0),
        )
    }
    fn post_navigation(&mut self, response: &egui::Response) {
        let max_tick = Tick::from_timetable_time(TimetableTime(366 * 86400)).0;
        self.x_offset = Tick(self.x_offset.0.clamp(
            -max_tick,
            max_tick - (response.rect.width() as f64 / self.zoom.x as f64) as i64,
        ));
        const TOP_BOTTOM_PADDING: f32 = 30.0;
        let v = if response.rect.height() / self.zoom_y()
            > (self.max_height.0 as f32 + TOP_BOTTOM_PADDING * 2.0 / self.zoom_y())
        {
            ((-response.rect.height() / self.zoom_y() + self.max_height.0 as f32) / 2.0) as f64
        } else {
            self.y_offset.0.clamp(
                (-TOP_BOTTOM_PADDING / self.zoom_y()) as f64,
                (self.max_height.0 as f32 - response.rect.height() / self.zoom_y()
                    + TOP_BOTTOM_PADDING / self.zoom_y()) as f64,
            )
        };
        self.y_offset.0 = v;
    }
}

impl Tab for DiagramTab {
    const NAME: &'static str = "Diagram";
    fn title(&self) -> WidgetText {
        "Diagram".into()
    }
    fn main_display(&mut self, app: &mut App, ui: &mut Ui) {
        ui.horizontal(|ui| {
            if ui.button("Update cache").clicked() {
                if let Some(route) = app.routes.get(&self.key) {
                    route.intervals.populate_trips(&app.snap, &mut self.cache);
                } else {
                    self.cache.map.clear();
                }
                self.callback.populate_entry_segments(&self.cache, &app.source);
            }
            if ui.button("Export PDF").clicked() {
                let fonts = ui.fonts(|fonts| {
                    let mut ret = Vec::new();
                    let defs = fonts.definitions();
                    if let Some(names) = defs.families.get(&egui::FontFamily::Proportional) {
                        for name in names {
                            let blob = &defs.font_data[name].font;
                            let bytes: &[u8] = (**blob).as_ref();
                            ret.push(std::borrow::Cow::Owned(bytes.to_vec()))
                        }
                    }
                    ret
                });
                paiagram_export::ExportGraphy {
                    snap: app.snap.clone(),
                    route: self.key,
                    cache: self.cache.clone(),
                    format: GraphyFormat::Pdf,
                    fonts,
                }
                .write_to_file::<false>(app.file_write_state.clone());
            }
        });
        Frame::canvas(ui.style())
            .inner_margin(Margin::ZERO)
            .outer_margin(Margin::ZERO)
            .stroke(Stroke::NONE)
            .show(ui, |ui| {
                main_display(self, app, ui);
            });
    }
}

fn draw_time_lines(painter: &mut Painter, navi: &DiagramTabNavigation) {
    const MAX_SCREEN_WIDTH: f64 = 64.0;
    const MIN_SCREEN_WIDTH: f64 = 32.0;
    let sizes = [
        Tick::from_timetable_time(TimetableTime(1)).0, // 1 second
        Tick::from_timetable_time(TimetableTime(10)).0, // 10 seconds
        Tick::from_timetable_time(TimetableTime(30)).0, // 30 seconds
        Tick::from_timetable_time(TimetableTime(60)).0, // 1 minute
        Tick::from_timetable_time(TimetableTime(60 * 5)).0, // 5 minutes
        Tick::from_timetable_time(TimetableTime(60 * 10)).0, // 10 minutes
        Tick::from_timetable_time(TimetableTime(60 * 30)).0, // 30 minutes
        Tick::from_timetable_time(TimetableTime(60 * 60)).0, // 1 hour
        Tick::from_timetable_time(TimetableTime(60 * 60 * 4)).0, // 4 hours
        Tick::from_timetable_time(TimetableTime(60 * 60 * 24)).0, // 1 day
    ];
    let visible_ticks = navi.visible_x();
    let ticks_per_screen_unit = navi.x_per_screen_unit_f64();
    let screen_rect = navi.visible_rect();
    let pixels_per_point = painter.pixels_per_point();
    let mut drawn: Vec<i64> = Vec::with_capacity(30);

    // align the first tick to a spacing boundary that is <= visible start.
    let first_visible_position = sizes
        .iter()
        .position(|s| *s as f64 / ticks_per_screen_unit * 1.5 > MIN_SCREEN_WIDTH)
        .unwrap_or(0);
    let visible = &sizes[first_visible_position..];
    for (i, spacing) in visible.iter().enumerate().rev() {
        let first = visible_ticks.start.0 - visible_ticks.start.0.rem_euclid(*spacing) - spacing;
        let mut tick = first;
        let strength = (((*spacing as f64 / ticks_per_screen_unit * 1.5) - MIN_SCREEN_WIDTH)
            / (MAX_SCREEN_WIDTH - MIN_SCREEN_WIDTH))
            .clamp(0.0, 1.0);
        if strength < 0.1 {
            continue;
        }
        // TODO: make stroke depend on current theme
        let mut current_stroke = Stroke {
            width: 0.6,
            color: Color32::GRAY,
        };
        if strength.is_finite() {
            // strange bug here
            current_stroke.color = current_stroke.color.gamma_multiply(strength as f32);
        }
        current_stroke.width = 0.5;
        while tick <= visible_ticks.end.0 {
            tick += *spacing;
            if drawn.contains(&tick) {
                continue;
            }
            let mut x = navi.logical_x_to_screen_x(Tick(tick));
            current_stroke.round_center_to_pixel(pixels_per_point, &mut x);
            painter.vline(x, screen_rect.top()..=screen_rect.bottom(), current_stroke);
            drawn.push(tick);
            let time = Tick(tick).to_timetable_time();
            let mut offset = screen_rect.top();
            let text = match i + first_visible_position {
                0..=2 => time.to_hmsd().2.to_string(),
                3..=8 => format!("{}:{:02}", time.to_hmsd().0, time.to_hmsd().1),
                9 => {
                    offset += 13.0;
                    time.to_string()
                }
                _ => unreachable!(),
            };
            painter.text(
                Pos2 { x, y: offset },
                Align2::CENTER_TOP,
                text,
                FontId::proportional(13.0),
                current_stroke.color,
            );
        }
    }
}

fn main_display(tab: &mut DiagramTab, app: &mut App, ui: &mut Ui) {
    let (response, mut painter) =
        ui.allocate_painter(ui.available_size_before_wrap(), Sense::click_and_drag());
    tab.navi.visible_rect = response.rect;
    tab.navi.handle_navigation(ui, &response);
    draw_time_lines(&mut painter, &tab.navi);

    let Some(route) = app.source.routes.get(&tab.key) else {
        return;
    };

    let mut station_height_so_far = CanvasLength::ZERO;
    let mut station_heights = Vec::with_capacity(route.intervals.0.len());
    let station_line_stroke = Stroke {
        width: 0.6,
        color: Color32::GRAY,
    };

    for interval in &route.intervals.0 {
        let Some(station) = (match &interval.station_record {
            StationRecord::All(key) => Some(*key),
            StationRecord::Some(nodes) => nodes
                .first()
                .and_then(|key| app.source.graph.nodes().get(key))
                .map(|wfc| wfc.parent),
        })
        .and_then(|key| app.source.stations.get(&key)) else {
            continue;
        };
        let mut y = tab.navi.logical_y_to_screen_y(station_height_so_far);
        station_line_stroke.round_center_to_pixel(ui.pixels_per_point(), &mut y);
        painter.hline(response.rect.x_range(), y, station_line_stroke);
        painter.text(
            Pos2 {
                x: response.rect.left(),
                y,
            },
            Align2::LEFT_BOTTOM,
            station.name.as_str(),
            FontId::proportional(13.0),
            station_line_stroke.color,
        );
        station_heights.push(station_height_so_far);
        station_height_so_far = CanvasLength(
            station_height_so_far.0
                + interval.canvas_length.unwrap_or_else(|| CanvasLength::from_cm(1.5)).0,
        );
    }

    tab.navi.max_height = station_height_so_far;

    // paint the station lines and diagram lines
    tab.callback.populate_stations(station_heights.iter().copied());
    tab.callback.populate_uniforms(&tab.navi, response.rect);
    painter.add(tab.callback.clone().paint_callback(response.rect));

    // selected item overlay
    let animation_progress = ui.animate_bool_responsive(
        ui.id().with("ui animation progress"),
        !matches!(app.selected_items, SelectedItems::None),
    );
    painter.rect_filled(
        response.rect,
        0,
        ui.visuals().extreme_bg_color.gamma_multiply(lerp(0.0..=0.5, animation_progress)),
    );

    // interactive zone
    if response.clicked()
        && let Some(pos) = response.interact_pointer_pos()
        // this makes sure that when already selecting item
        // the next action always deselects the item instead of focusing on new item
        && matches!(app.selected_items.take(), SelectedItems::None)
    {
        if let Some(trip_key) = select_trip_from_pos(tab, pos, &station_heights) {
            app.selected_items.replace(SelectedItem::Trip(trip_key));
        } else if false {
            // TODO
        } else if false {
            // TODO
        }
    }

    // display zone
    if let SelectedItems::Trips(trips) = &app.selected_items {
        for trip_key in trips {
            let Some(trip) = app.source.trips.get(trip_key) else {
                continue;
            };
            let stroke =
                trip.service_class.and_then(|key| app.source.service_classes.get(&key)).map_or(
                    Stroke::new(lerp(1.0..=5.0, animation_progress), Color32::GRAY),
                    |class| {
                        Stroke::new(
                            lerp((class.style.width as f32 * 1.0)..=5.0, animation_progress),
                            class.style.color,
                        )
                    },
                );
            let text_color = ui.visuals().text_color().gamma_multiply(animation_progress);
            for polyline in tab.cache.map.get(trip_key).iter().flat_map(|&it| it) {
                let points: Vec<_> = polyline
                    .iter()
                    .flat_map(|&(estimate, _entry, idx, progress)| {
                        let x1 = tab.navi.logical_x_to_screen_x(estimate.arr.to_ticks());
                        let x2 = tab.navi.logical_x_to_screen_x(estimate.dep.to_ticks());
                        let idx = idx as usize;
                        let curr_y = tab.navi.logical_y_to_screen_y(station_heights[idx]);
                        let next_y = tab.navi.logical_y_to_screen_y(station_heights[idx + 1]);
                        let y = lerp(curr_y..=next_y, progress);
                        [Pos2::new(x1, y), Pos2::new(x2, y)]
                    })
                    .collect();
                if let Some(&first) = points.first()
                    && let Some(&last) = points.last()
                    && let Some((estimate_first, ..)) = polyline.first()
                    && let Some((estimate_last, ..)) = polyline.last()
                {
                    let y_max = points
                        .iter()
                        .fold(first.y, |acc, pos| if pos.y > acc { pos.y } else { acc })
                        + 20.0;
                    painter.line(
                        vec![first, pos2(first.x, y_max), pos2(last.x, y_max), last],
                        Stroke::new(1.0, Color32::DARK_GREEN.gamma_multiply(animation_progress)),
                    );
                    painter.text(
                        pos2(first.x.max(response.rect.left()), y_max)
                            + Vec2::angled(-FRAC_PI_4) * 2.0,
                        Align2::LEFT_BOTTOM,
                        estimate_first.arr.to_string(),
                        FontId::proportional(13.0),
                        text_color,
                    );
                    painter.text(
                        pos2(first.x.max(response.rect.left()), y_max)
                            + Vec2::angled(FRAC_PI_4) * 2.0,
                        Align2::LEFT_TOP,
                        (estimate_last.dep - estimate_first.arr).to_string(),
                        FontId::proportional(13.0),
                        text_color,
                    );
                    painter.text(
                        pos2(last.x.min(response.rect.right()), y_max)
                            + Vec2::angled(-FRAC_PI_4 * 3.0) * 2.0,
                        Align2::RIGHT_BOTTOM,
                        (estimate_last.dep).to_string(),
                        FontId::proportional(13.0),
                        text_color,
                    );
                }
                painter.line(points.clone(), stroke);
                let (points, _) = points.as_chunks::<2>();
                for ((estimate, ..), (prev, curr, next)) in std::iter::zip(
                    polyline,
                    chain!([None], points.iter().map(Some), [None]).tuple_windows(),
                ) {
                    let &[pos_curr_arr, pos_curr_dep] = curr.unwrap();
                    let pos_prev_dep = prev.map_or(pos_curr_arr, |&[_, p]| p);
                    let pos_next_arr = next.map_or(pos_curr_dep, |&[p, _]| p);
                    if estimate.arr != estimate.dep {
                        let (align, direction) =
                            label_placement(pos_prev_dep, pos_curr_arr, pos_curr_dep);
                        painter.text(
                            pos_curr_arr + direction * 4.0,
                            align,
                            estimate.arr.to_string(),
                            FontId::proportional(13.0),
                            text_color,
                        );
                    }
                    let (align, direction) =
                        label_placement(pos_curr_arr, pos_curr_dep, pos_next_arr);
                    painter.text(
                        pos_curr_dep + direction * 4.0,
                        align,
                        estimate.dep.to_string(),
                        FontId::proportional(13.0),
                        text_color,
                    );
                }
            }
        }
    }
}

fn select_trip_from_pos(
    tab: &DiagramTab,
    ptr_pos: Pos2,
    station_heights: &[CanvasLength],
) -> Option<TripKey> {
    const SELECT_RADIUS: f32 = 7.0;
    // The same point mapping as when drawing (see the display zone in `main_display`), so that
    // what is selected matches what is drawn. Each entry spans `arr`..`dep` at one placement.
    let points = |estimate: &TEstimate, idx: u32, progress: f32| {
        let x1 = tab.navi.logical_x_to_screen_x(estimate.arr.to_ticks());
        let x2 = tab.navi.logical_x_to_screen_x(estimate.dep.to_ticks());
        let curr_y = tab.navi.logical_y_to_screen_y(station_heights[idx as usize]);
        let next_y = tab.navi.logical_y_to_screen_y(station_heights[idx as usize + 1]);
        let y = lerp(curr_y..=next_y, progress);
        [Pos2::new(x1, y), Pos2::new(x2, y)]
    };
    let hit = |p1: Pos2, p2: Pos2| {
        let diff = p2 - p1;
        let len_sq = diff.length_sq();
        let t = if len_sq > 0.0 {
            ((ptr_pos - p1).dot(diff) / len_sq).clamp(0.0, 1.0)
        } else {
            0.0
        };
        (p1 + t * diff - ptr_pos).length_sq() <= SELECT_RADIUS * SELECT_RADIUS
    };
    for (trip_key, polyline) in
        tab.cache.map.iter().flat_map(|(k, v)| std::iter::zip(std::iter::repeat(k), v))
    {
        for [curr, next] in polyline.array_windows::<2>() {
            let [curr_arr, curr_dep] = points(&curr.0, curr.2, curr.3);
            let [next_arr, next_dep] = points(&next.0, next.2, next.3);
            // The segments the drawing produces between two consecutive entries: the dwell at
            // the first, the travel between them, and the dwell at the second.
            if hit(curr_arr, curr_dep) || hit(curr_dep, next_arr) || hit(next_arr, next_dep) {
                return Some(*trip_key);
            }
        }
    }
    None
}
