// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.3
// Changes made to this file will not be saved.
// SourceHash: d918f10c797199a406918c19f6efef0fc471aa83cccd7730bc3ecdca23beff00

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    GraphIntervals,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::GraphIntervals => graph_intervals::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::GraphIntervals => graph_intervals::create_shader_module_embed_source(device),
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        );
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
    use super::_root;
    use super::_root::*;
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const GRAPH_INTERVALS_INTERVAL_POINT_ASSERTS: () = {
        assert!(std::mem::offset_of!(graph_intervals::IntervalPoint, screen_pos) == 0);
        assert!(std::mem::offset_of!(graph_intervals::IntervalPoint, connects_to_next) == 8);
        assert!(std::mem::align_of::<graph_intervals::IntervalPoint>() == 8);
        assert!(std::mem::size_of::<graph_intervals::IntervalPoint>() == 16);
    };
    const GRAPH_INTERVALS_UNIFORMS_ASSERTS: () = {
        assert!(std::mem::offset_of!(graph_intervals::Uniforms, screen_size) == 0);
        assert!(std::mem::offset_of!(graph_intervals::Uniforms, pixels_per_point) == 8);
        assert!(std::mem::align_of::<graph_intervals::Uniforms>() == 8);
        assert!(std::mem::size_of::<graph_intervals::Uniforms>() == 16);
    };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod graph_intervals {
    use super::_root;
    use super::_root::*;
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct IntervalPoint {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_pos: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `u32`"]
        pub connects_to_next: u32,
        pub _pad_connects_to_next: [u8; 8 - ::core::mem::size_of::<u32>()],
    }
    impl IntervalPoint {
        pub const fn new(screen_pos: [f32; 2], connects_to_next: u32) -> Self {
            Self {
                screen_pos,
                connects_to_next,
                _pad_connects_to_next: [0; 8 - ::core::mem::size_of::<u32>()],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct IntervalPointInit {
        pub screen_pos: [f32; 2],
        pub connects_to_next: u32,
    }
    impl IntervalPointInit {
        pub fn build(&self) -> IntervalPoint {
            IntervalPoint {
                screen_pos: self.screen_pos,
                connects_to_next: self.connects_to_next,
                _pad_connects_to_next: [0; 8 - ::core::mem::size_of::<u32>()],
            }
        }
    }
    impl From<IntervalPointInit> for IntervalPoint {
        fn from(data: IntervalPointInit) -> Self {
            data.build()
        }
    }
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Uniforms {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_size: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `f32`"]
        pub pixels_per_point: f32,
        pub _pad_pixels_per_point: [u8; 8 - ::core::mem::size_of::<f32>()],
    }
    impl Uniforms {
        pub const fn new(screen_size: [f32; 2], pixels_per_point: f32) -> Self {
            Self {
                screen_size,
                pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct UniformsInit {
        pub screen_size: [f32; 2],
        pub pixels_per_point: f32,
    }
    impl UniformsInit {
        pub fn build(&self) -> Uniforms {
            Uniforms {
                screen_size: self.screen_size,
                pixels_per_point: self.pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    impl From<UniformsInit> for Uniforms {
        fn from(data: UniformsInit) -> Self {
            data.build()
        }
    }
    pub const LINE_THICKNESS: f32 = 2f32;
    pub const FEATHER_WIDTH_PX: f32 = 2f32;
    pub const SQUARE_MESH_LENGTH: u32 = 4u32;
    pub const SEGMENT_MESH_LENGTH: u32 = 6u32;
    pub const SEGMENT_MESH_CONNECT_START: u32 = 4u32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub interval_points: wgpu::BufferBinding<'a>,
        pub uniforms: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub interval_points: wgpu::BindGroupEntry<'a>,
        pub uniforms: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                interval_points: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.interval_points),
                },
                uniforms: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.uniforms),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
            [self.interval_points, self.uniforms]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("GraphIntervals::BindGroup0::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(1): \"interval_points\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    #[doc = " @binding(0): \"uniforms\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::graph_intervals::Uniforms,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("GraphIntervals::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 1],
        ) -> [wgpu::BindGroupLayout; 1] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("GraphIntervals::PipelineLayout"),
            bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("graph_intervals.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct IntervalPoint {
    screen_pos: vec2<f32>,
    connects_to_next: u32,
}

struct VertexOut {
    @location(0) color: vec4<f32>,
    @location(1) offset: f32,
    @location(2) half_width: f32,
    @builtin(position) position: vec4<f32>,
}

struct Uniforms {
    screen_size: vec2<f32>,
    pixels_per_point: f32,
}

struct SegmentMeshVertex {
    along: f32,
    side: f32,
}

const LINE_THICKNESS: f32 = 2f;
const LINE_COLOR: vec4<f32> = vec4<f32>(0.23f, 0.55f, 0.95f, 1f);
const FEATHER_WIDTH_PX: f32 = 2f;
const SQUARE_CORNERS: array<vec2<f32>, 4> = array<vec2<f32>, 4>(vec2<f32>(-1f, -1f), vec2<f32>(1f, -1f), vec2<f32>(-1f, 1f), vec2<f32>(1f, 1f));
const SQUARE_MESH_LENGTH: u32 = 4u;
const SEGMENT_MESH_VERTICES: array<SegmentMeshVertex, 4> = array<SegmentMeshVertex, 4>(SegmentMeshVertex(0f, 1f), SegmentMeshVertex(0f, -1f), SegmentMeshVertex(1f, 1f), SegmentMeshVertex(1f, -1f));
const SEGMENT_MESH_LENGTH: u32 = 6u;
const SEGMENT_MESH_INDICES: array<u32, 6> = array<u32, 6>(0u, 1u, 2u, 3u, 2u, 3u);
const SEGMENT_MESH_CONNECT_START: u32 = 4u;

@group(0) @binding(1) 
var<storage> interval_points: array<IntervalPoint>;
@group(0) @binding(0) 
var<uniform> uniforms: Uniforms;

fn line_feather(pixels_per_point: f32) -> f32 {
    return (FEATHER_WIDTH_PX / max(pixels_per_point, 0.000001f));
}

fn normalize_or(v: vec2<f32>, fallback: vec2<f32>) -> vec2<f32> {
    let len = length(v);
    if (len < 0.00001f) {
        return fallback;
    }
    return (v / vec2(len));
}

fn left_normal(dir: vec2<f32>) -> vec2<f32> {
    return vec2<f32>(-(dir.y), dir.x);
}

fn segment_quad_pos(p0_: vec2<f32>, p1_: vec2<f32>, corner: vec2<f32>, half_extent: f32) -> vec2<f32> {
    let _e6 = normalize_or((p1_ - p0_), vec2<f32>(1f, 0f));
    let _e7 = left_normal(_e6);
    let center = ((p0_ + p1_) * 0.5f);
    let half_len = (length((p1_ - p0_)) * 0.5f);
    return ((center + (_e6 * (corner.x * half_len))) + (_e7 * (corner.y * half_extent)));
}

fn screen_pos_to_clip(screen_pos_1: vec2<f32>) -> vec2<f32> {
    let _e5 = uniforms.screen_size.x;
    let clip_x = (((screen_pos_1.x / _e5) * 2f) - 1f);
    let _e15 = uniforms.screen_size.y;
    let clip_y = (1f - ((screen_pos_1.y / _e15) * 2f));
    return vec2<f32>(clip_x, clip_y);
}

fn line_alpha(offset: f32, half_width: f32, feather: f32) -> f32 {
    return (1f - smoothstep((half_width - (feather * 0.5f)), (half_width + (feather * 0.5f)), abs(offset)));
}

fn joint_vertex(p: vec2<f32>, dir_in: vec2<f32>, dir_out: vec2<f32>, side: f32, half_width_1: f32) -> vec2<f32> {
    let _e1 = left_normal(dir_in);
    let n_in = (_e1 * side);
    let _e5 = left_normal(dir_out);
    let n_out = (_e5 * side);
    let denom = max((1f + dot(dir_in, dir_out)), 0.25f);
    return (p + ((half_width_1 * (n_in + n_out)) / vec2(denom)));
}

@vertex 
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32) -> VertexOut {
    var screen_pos: vec2<f32>;

    let point = interval_points[instance_index];
    let _e6 = uniforms.pixels_per_point;
    let _e7 = line_feather(_e6);
    let half_extent_1 = (1f + (_e7 * 0.5f));
    let start = point.screen_pos;
    let corner_1 = SQUARE_CORNERS[vertex_index];
    let offset_1 = (corner_1.y * half_extent_1);
    screen_pos = start;
    if (point.connects_to_next != 0u) {
        let end = interval_points[(instance_index + 1u)].screen_pos;
        let _e28 = segment_quad_pos(start, end, corner_1, half_extent_1);
        screen_pos = _e28;
    }
    let _e29 = screen_pos;
    let _e30 = screen_pos_to_clip(_e29);
    return VertexOut(LINE_COLOR, offset_1, 1f, vec4<f32>(_e30, 0f, 1f));
}

@fragment 
fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
    let _e2 = uniforms.pixels_per_point;
    let _e3 = line_feather(_e2);
    let _e7 = line_alpha(in.offset, in.half_width, _e3);
    return vec4<f32>(in.color.xyz, (in.color.w * _e7));
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
    use super::_root;
    use super::_root::*;
    unsafe impl bytemuck::Zeroable for graph_intervals::IntervalPoint {}
    unsafe impl bytemuck::Pod for graph_intervals::IntervalPoint {}
    unsafe impl bytemuck::Zeroable for graph_intervals::Uniforms {}
    unsafe impl bytemuck::Pod for graph_intervals::Uniforms {}
}
