// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.3
// Changes made to this file will not be saved.
// SourceHash: 78092cbb957b82f3a3042662234ceebfacfd51bbf041e6b111cd8a1196bcbb15

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    GraphNodes,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::GraphNodes => graph_nodes::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::GraphNodes => graph_nodes::create_shader_module_embed_source(device),
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        );
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
    use super::_root;
    use super::_root::*;
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const GRAPH_NODES_NODE_POINT_ASSERTS: () = {
        assert!(std::mem::offset_of!(graph_nodes::NodePoint, screen_pos) == 0);
        assert!(std::mem::align_of::<graph_nodes::NodePoint>() == 8);
        assert!(std::mem::size_of::<graph_nodes::NodePoint>() == 8);
    };
    const GRAPH_NODES_UNIFORMS_ASSERTS: () = {
        assert!(std::mem::offset_of!(graph_nodes::Uniforms, screen_size) == 0);
        assert!(std::mem::offset_of!(graph_nodes::Uniforms, pixels_per_point) == 8);
        assert!(std::mem::align_of::<graph_nodes::Uniforms>() == 8);
        assert!(std::mem::size_of::<graph_nodes::Uniforms>() == 16);
    };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod graph_nodes {
    use super::_root;
    use super::_root::*;
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct NodePoint {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_pos: [f32; 2],
    }
    impl NodePoint {
        pub const fn new(screen_pos: [f32; 2]) -> Self {
            Self { screen_pos }
        }
    }
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Uniforms {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_size: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `f32`"]
        pub pixels_per_point: f32,
        pub _pad_pixels_per_point: [u8; 8 - ::core::mem::size_of::<f32>()],
    }
    impl Uniforms {
        pub const fn new(screen_size: [f32; 2], pixels_per_point: f32) -> Self {
            Self {
                screen_size,
                pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct UniformsInit {
        pub screen_size: [f32; 2],
        pub pixels_per_point: f32,
    }
    impl UniformsInit {
        pub fn build(&self) -> Uniforms {
            Uniforms {
                screen_size: self.screen_size,
                pixels_per_point: self.pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    impl From<UniformsInit> for Uniforms {
        fn from(data: UniformsInit) -> Self {
            data.build()
        }
    }
    pub const NODE_HALF_SIZE: f32 = 4f32;
    pub const SQUARE_MESH_LENGTH: u32 = 4u32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub node_points: wgpu::BufferBinding<'a>,
        pub uniforms: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub node_points: wgpu::BindGroupEntry<'a>,
        pub uniforms: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                node_points: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.node_points),
                },
                uniforms: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.uniforms),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 2] {
            [self.node_points, self.uniforms]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("GraphNodes::BindGroup0::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(1): \"node_points\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    #[doc = " @binding(0): \"uniforms\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::graph_nodes::Uniforms,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("GraphNodes::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 1],
        ) -> [wgpu::BindGroupLayout; 1] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("GraphNodes::PipelineLayout"),
            bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("graph_nodes.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct NodePoint {
    screen_pos: vec2<f32>,
}

struct VertexOut {
    @location(0) color: vec4<f32>,
    @builtin(position) position: vec4<f32>,
}

struct Uniforms {
    screen_size: vec2<f32>,
    pixels_per_point: f32,
}

const NODE_HALF_SIZE: f32 = 4f;
const PLATFORM_COLOR: vec4<f32> = vec4<f32>(0.9f, 0.9f, 0.9f, 1f);
const SWITCH_COLOR: vec4<f32> = vec4<f32>(0.35f, 0.35f, 0.35f, 1f);
const SQUARE_CORNERS: array<vec2<f32>, 4> = array<vec2<f32>, 4>(vec2<f32>(-1f, -1f), vec2<f32>(1f, -1f), vec2<f32>(-1f, 1f), vec2<f32>(1f, 1f));
const SQUARE_MESH_LENGTH: u32 = 4u;

@group(0) @binding(1) 
var<storage> node_points: array<NodePoint>;
@group(0) @binding(0) 
var<uniform> uniforms: Uniforms;

fn screen_pos_to_clip(screen_pos: vec2<f32>) -> vec2<f32> {
    let _e5 = uniforms.screen_size.x;
    let clip_x = (((screen_pos.x / _e5) * 2f) - 1f);
    let _e15 = uniforms.screen_size.y;
    let clip_y = (1f - ((screen_pos.y / _e15) * 2f));
    return vec2<f32>(clip_x, clip_y);
}

@vertex 
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32) -> VertexOut {
    var color: vec4<f32> = PLATFORM_COLOR;

    let node = node_points[instance_index];
    let corner = SQUARE_CORNERS[vertex_index];
    let screen_pos_1 = (node.screen_pos + (corner * NODE_HALF_SIZE));
    let _e12 = screen_pos_to_clip(screen_pos_1);
    let _e14 = color;
    return VertexOut(_e14, vec4<f32>(_e12, 0f, 1f));
}

@fragment 
fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
    return in.color;
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
    use super::_root;
    use super::_root::*;
    unsafe impl bytemuck::Zeroable for graph_nodes::NodePoint {}
    unsafe impl bytemuck::Pod for graph_nodes::NodePoint {}
    unsafe impl bytemuck::Zeroable for graph_nodes::Uniforms {}
    unsafe impl bytemuck::Pod for graph_nodes::Uniforms {}
}
