#!/usr/bin/env bash
DATE=$(date --iso-8601=s)
grep -oP '^Operation.+B=\K.*$' "$1" | tr ',' '\n' | sort | uniq > ${2:-"before_$DATE.txt"}
grep -oP '^Operation.+A=\K.*$' "$1" | tr ',' '\n' | sort | uniq > ${3:-"after_$DATE.txt"}
grep -oP '^\KOperation.+[AB](?==)' "$1" | sort | uniq > ${4:-"group_$DATE.txt"}
grep -oP '^EkiJikoku=\K.*$' "$1" | tr ',' '\n' | sort | uniq > ${5:-"times_$DATE.txt"}
