// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.3
// Changes made to this file will not be saved.
// SourceHash: 392729443e4c48c09410a37f0a2ac819efc871f95250b34332f0f8c5492e3124

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    GpuTrip,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::GpuTrip => gpu_trip::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::GpuTrip => gpu_trip::create_shader_module_embed_source(device),
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        );
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
    use super::_root;
    use super::_root::*;
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const GPU_TRIP_UNIFORMS_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, screen_size) == 0);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, ticks_min) == 8);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, canvas_length_min) == 12);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, x_per_tick) == 16);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, entry_segment_count) == 20);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, y_per_canvas_length) == 24);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, pixels_per_point) == 28);
        assert!(std::mem::align_of::<gpu_trip::Uniforms>() == 8);
        assert!(std::mem::size_of::<gpu_trip::Uniforms>() == 32);
    };
    const GPU_TRIP_CANVAS_LENGTH_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::CanvasLength, value) == 0);
        assert!(std::mem::align_of::<gpu_trip::CanvasLength>() == 4);
        assert!(std::mem::size_of::<gpu_trip::CanvasLength>() == 4);
    };
    const GPU_TRIP_STYLE_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::Style, thickness) == 0);
        assert!(std::mem::offset_of!(gpu_trip::Style, fill_rgba) == 4);
        assert!(std::mem::align_of::<gpu_trip::Style>() == 4);
        assert!(std::mem::size_of::<gpu_trip::Style>() == 8);
    };
    const GPU_TRIP_ENTRY_SEGMENT_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, curr_time_seconds) == 0);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, curr_index) == 4);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, curr_progress) == 8);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, next_time_seconds) == 12);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, next_index) == 16);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, next_progress) == 20);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, style) == 24);
        assert!(std::mem::align_of::<gpu_trip::EntrySegment>() == 4);
        assert!(std::mem::size_of::<gpu_trip::EntrySegment>() == 32);
    };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod gpu_trip {
    use super::_root;
    use super::_root::*;
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Uniforms {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_size: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `i32`"]
        pub ticks_min: i32,
        #[doc = "offset: 12, size: 4, type: `f32`"]
        pub canvas_length_min: f32,
        #[doc = "offset: 16, size: 4, type: `f32`"]
        pub x_per_tick: f32,
        #[doc = "offset: 20, size: 4, type: `u32`"]
        pub entry_segment_count: u32,
        #[doc = "offset: 24, size: 4, type: `f32`"]
        pub y_per_canvas_length: f32,
        #[doc = "offset: 28, size: 4, type: `f32`"]
        pub pixels_per_point: f32,
    }
    impl Uniforms {
        pub const fn new(
            screen_size: [f32; 2],
            ticks_min: i32,
            canvas_length_min: f32,
            x_per_tick: f32,
            entry_segment_count: u32,
            y_per_canvas_length: f32,
            pixels_per_point: f32,
        ) -> Self {
            Self {
                screen_size,
                ticks_min,
                canvas_length_min,
                x_per_tick,
                entry_segment_count,
                y_per_canvas_length,
                pixels_per_point,
            }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct CanvasLength {
        #[doc = "offset: 0, size: 4, type: `f32`"]
        pub value: f32,
    }
    impl CanvasLength {
        pub const fn new(value: f32) -> Self {
            Self { value }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Style {
        #[doc = "offset: 0, size: 4, type: `f32`"]
        pub thickness: f32,
        #[doc = "offset: 4, size: 4, type: `u32`"]
        pub fill_rgba: u32,
    }
    impl Style {
        pub const fn new(thickness: f32, fill_rgba: u32) -> Self {
            Self {
                thickness,
                fill_rgba,
            }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct EntrySegment {
        #[doc = "offset: 0, size: 4, type: `i32`"]
        pub curr_time_seconds: i32,
        #[doc = "offset: 4, size: 4, type: `u32`"]
        pub curr_index: u32,
        #[doc = "offset: 8, size: 4, type: `f32`"]
        pub curr_progress: f32,
        #[doc = "offset: 12, size: 4, type: `i32`"]
        pub next_time_seconds: i32,
        #[doc = "offset: 16, size: 4, type: `u32`"]
        pub next_index: u32,
        #[doc = "offset: 20, size: 4, type: `f32`"]
        pub next_progress: f32,
        #[doc = "offset: 24, size: 8, type: `Style`"]
        pub style: Style,
    }
    impl EntrySegment {
        pub const fn new(
            curr_time_seconds: i32,
            curr_index: u32,
            curr_progress: f32,
            next_time_seconds: i32,
            next_index: u32,
            next_progress: f32,
            style: Style,
        ) -> Self {
            Self {
                curr_time_seconds,
                curr_index,
                curr_progress,
                next_time_seconds,
                next_index,
                next_progress,
                style,
            }
        }
    }
    pub const SEGMENT_MESH_LENGTH: u32 = 6u32;
    pub const FEATHER_WIDTH_PX: f32 = 2f32;
    pub const TICKS_PER_SECOND: i32 = 100i32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub uniforms: wgpu::BufferBinding<'a>,
        pub entry_segments: wgpu::BufferBinding<'a>,
        pub stations: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub uniforms: wgpu::BindGroupEntry<'a>,
        pub entry_segments: wgpu::BindGroupEntry<'a>,
        pub stations: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                uniforms: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.uniforms),
                },
                entry_segments: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.entry_segments),
                },
                stations: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.stations),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 3] {
            [self.uniforms, self.entry_segments, self.stations]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("GpuTrip::BindGroup0::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"uniforms\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::gpu_trip::Uniforms,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                    #[doc = " @binding(1): \"entry_segments\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    #[doc = " @binding(2): \"stations\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("GpuTrip::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 1],
        ) -> [wgpu::BindGroupLayout; 1] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("GpuTrip::PipelineLayout"),
            bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("gpu_trip.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct Uniforms {
    screen_size: vec2<f32>,
    ticks_min: i32,
    canvas_length_min: f32,
    x_per_tick: f32,
    entry_segment_count: u32,
    y_per_canvas_length: f32,
    pixels_per_point: f32,
}

struct Tick {
    value: i32,
}

struct CanvasLength {
    value: f32,
}

struct Style {
    thickness: f32,
    fill_rgba: u32,
}

struct EntrySegment {
    curr_time_seconds: i32,
    curr_index: u32,
    curr_progress: f32,
    next_time_seconds: i32,
    next_index: u32,
    next_progress: f32,
    style: Style,
}

struct SegmentMeshVertex {
    along: f32,
    side: f32,
}

struct VertexOut {
    @location(0) color: vec4<f32>,
    @location(1) offset: f32,
    @location(2) half_width: f32,
    @builtin(position) position: vec4<f32>,
}

const SEGMENT_MESH_VERTICES: array<SegmentMeshVertex, 4> = array<SegmentMeshVertex, 4>(SegmentMeshVertex(0f, 1f), SegmentMeshVertex(0f, -1f), SegmentMeshVertex(1f, 1f), SegmentMeshVertex(1f, -1f));
const SEGMENT_MESH_LENGTH: u32 = 6u;
const SEGMENT_MESH_INDICES: array<u32, 6> = array<u32, 6>(0u, 1u, 2u, 1u, 3u, 2u);
const FEATHER_WIDTH_PX: f32 = 2f;
const TICKS_PER_SECOND: i32 = 100i;

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;
@group(0) @binding(1)
var<storage> entry_segments: array<EntrySegment>;
@group(0) @binding(2)
var<storage> stations: array<CanvasLength>;

fn seconds_to_screen_x(secs: i32) -> f32 {
    let ticks = (secs * TICKS_PER_SECOND);
    let _e5 = uniforms.ticks_min;
    let _e10 = uniforms.x_per_tick;
    return (f32((ticks - _e5)) / _e10);
}

fn height_to_screen_y(height: CanvasLength) -> f32 {
    let _e4 = uniforms.canvas_length_min;
    let _e8 = uniforms.y_per_canvas_length;
    return ((height.value - _e4) / _e8);
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32) -> VertexOut {
    let entry = entry_segments[instance_index];
    let _e7 = stations[entry.curr_index];
    let _e8 = height_to_screen_y(_e7);
    let _e14 = stations[(entry.curr_index + 1u)];
    let _e15 = height_to_screen_y(_e14);
    let y0_ = mix(_e8, _e15, entry.curr_progress);
    let _e21 = stations[entry.next_index];
    let _e22 = height_to_screen_y(_e21);
    let _e26 = stations[entry.next_index];
    let _e27 = height_to_screen_y(_e26);
    let y1_ = mix(_e22, _e27, entry.next_progress);
    let _e31 = seconds_to_screen_x(entry.curr_time_seconds);
    let _e33 = seconds_to_screen_x(entry.next_time_seconds);
    let p0_ = vec2<f32>(_e31, y0_);
    let p1_ = vec2<f32>(_e33, y1_);
    let dir = (p1_ - p0_);
    let inv_len = inverseSqrt(max(dot(dir, dir), 0.000000000001f));
    let normal = vec2<f32>((-(dir.y) * inv_len), (dir.x * inv_len));
    let mesh_index = SEGMENT_MESH_INDICES[vertex_index];
    let mesh = SEGMENT_MESH_VERTICES[mesh_index];
    let _e54 = uniforms.pixels_per_point;
    let feather = (FEATHER_WIDTH_PX / max(_e54, 0.000001f));
    let half_width = (entry.style.thickness * 0.5f);
    let offset = (mesh.side * (half_width + (feather * 0.5f)));
    let base_pos = mix(p0_, p1_, mesh.along);
    let world_pos = (base_pos + (normal * offset));
    let _e76 = uniforms.screen_size.x;
    let clip_x = (((world_pos.x / _e76) * 2f) - 1f);
    let _e86 = uniforms.screen_size.y;
    let clip_y = (1f - ((world_pos.y / _e86) * 2f));
    let rgba = entry.style.fill_rgba;
    let color = vec4<f32>((f32(((rgba >> 24u) & 255u)) / 255f), (f32(((rgba >> 16u) & 255u)) / 255f), (f32(((rgba >> 8u) & 255u)) / 255f), (f32((rgba & 255u)) / 255f));
    return VertexOut(color, offset, half_width, vec4<f32>(clip_x, clip_y, 0f, 1f));
}

@fragment
fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
    let _e2 = uniforms.pixels_per_point;
    let feather_1 = (FEATHER_WIDTH_PX / max(_e2, 0.000001f));
    let alpha = (1f - smoothstep((in.half_width - (feather_1 * 0.5f)), (in.half_width + (feather_1 * 0.5f)), abs(in.offset)));
    return vec4<f32>(in.color.xyz, (in.color.w * alpha));
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
    use super::_root;
    use super::_root::*;
    unsafe impl bytemuck::Zeroable for gpu_trip::Uniforms {}
    unsafe impl bytemuck::Pod for gpu_trip::Uniforms {}
    unsafe impl bytemuck::Zeroable for gpu_trip::CanvasLength {}
    unsafe impl bytemuck::Pod for gpu_trip::CanvasLength {}
    unsafe impl bytemuck::Zeroable for gpu_trip::Style {}
    unsafe impl bytemuck::Pod for gpu_trip::Style {}
    unsafe impl bytemuck::Zeroable for gpu_trip::EntrySegment {}
    unsafe impl bytemuck::Pod for gpu_trip::EntrySegment {}
}
