// File automatically generated by wgsl_bindgen^
//
// ^ wgsl_bindgen version 0.23.3
// Changes made to this file will not be saved.
// SourceHash: 31b03a260d3e168f63a33c36c8e411f721be497223364f16334cd6e67a262290

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ShaderEntry {
    GpuTrip,
}
impl ShaderEntry {
    pub fn create_pipeline_layout(&self, device: &wgpu::Device) -> wgpu::PipelineLayout {
        match self {
            Self::GpuTrip => gpu_trip::create_pipeline_layout(device),
        }
    }
    pub fn create_shader_module_embed_source(&self, device: &wgpu::Device) -> wgpu::ShaderModule {
        match self {
            Self::GpuTrip => gpu_trip::create_shader_module_embed_source(device),
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
mod _root {
    pub use super::*;
    pub trait SetBindGroup {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        );
    }
    impl SetBindGroup for wgpu::RenderPass<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
    impl SetBindGroup for wgpu::RenderBundleEncoder<'_> {
        fn set_bind_group(
            &mut self,
            index: u32,
            bind_group: &wgpu::BindGroup,
            offsets: &[wgpu::DynamicOffset],
        ) {
            self.set_bind_group(index, bind_group, offsets);
        }
    }
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod layout_asserts {
    use super::_root;
    use super::_root::*;
    const WGSL_BASE_TYPE_ASSERTS: () = {};
    const GPU_TRIP_UNIFORMS_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, screen_size) == 0);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, ticks_min) == 8);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, canvas_length_min) == 12);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, x_per_tick) == 16);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, y_per_canvas_length) == 20);
        assert!(std::mem::offset_of!(gpu_trip::Uniforms, pixels_per_point) == 24);
        assert!(std::mem::align_of::<gpu_trip::Uniforms>() == 8);
        assert!(std::mem::size_of::<gpu_trip::Uniforms>() == 32);
    };
    const GPU_TRIP_CANVAS_LENGTH_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::CanvasLength, value) == 0);
        assert!(std::mem::align_of::<gpu_trip::CanvasLength>() == 4);
        assert!(std::mem::size_of::<gpu_trip::CanvasLength>() == 4);
    };
    const GPU_TRIP_STYLE_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::Style, thickness) == 0);
        assert!(std::mem::offset_of!(gpu_trip::Style, fill_rgba) == 4);
        assert!(std::mem::align_of::<gpu_trip::Style>() == 4);
        assert!(std::mem::size_of::<gpu_trip::Style>() == 8);
    };
    const GPU_TRIP_ENTRY_SEGMENT_ASSERTS: () = {
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, arr_seconds) == 0);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, dep_seconds) == 4);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, curr_index) == 8);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, curr_progress) == 12);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, connects_to_prev) == 16);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, connects_to_next) == 20);
        assert!(std::mem::offset_of!(gpu_trip::EntrySegment, style) == 24);
        assert!(std::mem::align_of::<gpu_trip::EntrySegment>() == 4);
        assert!(std::mem::size_of::<gpu_trip::EntrySegment>() == 32);
    };
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod gpu_trip {
    use super::_root;
    use super::_root::*;
    #[repr(C, align(8))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Uniforms {
        #[doc = "offset: 0, size: 8, type: `vec2<f32>`"]
        pub screen_size: [f32; 2],
        #[doc = "offset: 8, size: 4, type: `i32`"]
        pub ticks_min: i32,
        #[doc = "offset: 12, size: 4, type: `f32`"]
        pub canvas_length_min: f32,
        #[doc = "offset: 16, size: 4, type: `f32`"]
        pub x_per_tick: f32,
        #[doc = "offset: 20, size: 4, type: `f32`"]
        pub y_per_canvas_length: f32,
        #[doc = "offset: 24, size: 4, type: `f32`"]
        pub pixels_per_point: f32,
        pub _pad_pixels_per_point: [u8; 8 - ::core::mem::size_of::<f32>()],
    }
    impl Uniforms {
        pub const fn new(
            screen_size: [f32; 2],
            ticks_min: i32,
            canvas_length_min: f32,
            x_per_tick: f32,
            y_per_canvas_length: f32,
            pixels_per_point: f32,
        ) -> Self {
            Self {
                screen_size,
                ticks_min,
                canvas_length_min,
                x_per_tick,
                y_per_canvas_length,
                pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    #[repr(C)]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct UniformsInit {
        pub screen_size: [f32; 2],
        pub ticks_min: i32,
        pub canvas_length_min: f32,
        pub x_per_tick: f32,
        pub y_per_canvas_length: f32,
        pub pixels_per_point: f32,
    }
    impl UniformsInit {
        pub fn build(&self) -> Uniforms {
            Uniforms {
                screen_size: self.screen_size,
                ticks_min: self.ticks_min,
                canvas_length_min: self.canvas_length_min,
                x_per_tick: self.x_per_tick,
                y_per_canvas_length: self.y_per_canvas_length,
                pixels_per_point: self.pixels_per_point,
                _pad_pixels_per_point: [0; 8 - ::core::mem::size_of::<f32>()],
            }
        }
    }
    impl From<UniformsInit> for Uniforms {
        fn from(data: UniformsInit) -> Self {
            data.build()
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct CanvasLength {
        #[doc = "offset: 0, size: 4, type: `f32`"]
        pub value: f32,
    }
    impl CanvasLength {
        pub const fn new(value: f32) -> Self {
            Self { value }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct Style {
        #[doc = "offset: 0, size: 4, type: `f32`"]
        pub thickness: f32,
        #[doc = "offset: 4, size: 4, type: `u32`"]
        pub fill_rgba: u32,
    }
    impl Style {
        pub const fn new(thickness: f32, fill_rgba: u32) -> Self {
            Self {
                thickness,
                fill_rgba,
            }
        }
    }
    #[repr(C, align(4))]
    #[derive(Debug, PartialEq, Clone, Copy)]
    pub struct EntrySegment {
        #[doc = "offset: 0, size: 4, type: `i32`"]
        pub arr_seconds: i32,
        #[doc = "offset: 4, size: 4, type: `i32`"]
        pub dep_seconds: i32,
        #[doc = "offset: 8, size: 4, type: `u32`"]
        pub curr_index: u32,
        #[doc = "offset: 12, size: 4, type: `f32`"]
        pub curr_progress: f32,
        #[doc = "offset: 16, size: 4, type: `u32`"]
        pub connects_to_prev: u32,
        #[doc = "offset: 20, size: 4, type: `u32`"]
        pub connects_to_next: u32,
        #[doc = "offset: 24, size: 8, type: `Style`"]
        pub style: Style,
    }
    impl EntrySegment {
        pub const fn new(
            arr_seconds: i32,
            dep_seconds: i32,
            curr_index: u32,
            curr_progress: f32,
            connects_to_prev: u32,
            connects_to_next: u32,
            style: Style,
        ) -> Self {
            Self {
                arr_seconds,
                dep_seconds,
                curr_index,
                curr_progress,
                connects_to_prev,
                connects_to_next,
                style,
            }
        }
    }
    pub const TICKS_PER_SECOND: i32 = 100i32;
    pub const FEATHER_WIDTH_PX: f32 = 2f32;
    pub const SEGMENT_MESH_CONNECT_START: u32 = 4u32;
    pub const SEGMENT_MESH_LENGTH: u32 = 6u32;
    pub const ENTRY_VS_MAIN: &str = "vs_main";
    pub const ENTRY_FS_MAIN: &str = "fs_main";
    #[derive(Debug)]
    pub struct VertexEntry<const N: usize> {
        pub entry_point: &'static str,
        pub buffers: [Option<wgpu::VertexBufferLayout<'static>>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn vertex_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a VertexEntry<N>,
    ) -> wgpu::VertexState<'a> {
        wgpu::VertexState {
            module,
            entry_point: Some(entry.entry_point),
            buffers: &entry.buffers,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn vs_main_entry() -> VertexEntry<0> {
        VertexEntry {
            entry_point: ENTRY_VS_MAIN,
            buffers: [],
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct FragmentEntry<const N: usize> {
        pub entry_point: &'static str,
        pub targets: [Option<wgpu::ColorTargetState>; N],
        pub constants: Vec<(&'static str, f64)>,
    }
    pub fn fragment_state<'a, const N: usize>(
        module: &'a wgpu::ShaderModule,
        entry: &'a FragmentEntry<N>,
    ) -> wgpu::FragmentState<'a> {
        wgpu::FragmentState {
            module,
            entry_point: Some(entry.entry_point),
            targets: &entry.targets,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &entry.constants,
                ..Default::default()
            },
        }
    }
    pub fn fs_main_entry(targets: [Option<wgpu::ColorTargetState>; 1]) -> FragmentEntry<1> {
        FragmentEntry {
            entry_point: ENTRY_FS_MAIN,
            targets,
            constants: Default::default(),
        }
    }
    #[derive(Debug)]
    pub struct WgpuBindGroup0EntriesParams<'a> {
        pub uniforms: wgpu::BufferBinding<'a>,
        pub entry_segments: wgpu::BufferBinding<'a>,
        pub stations: wgpu::BufferBinding<'a>,
    }
    #[derive(Clone, Debug)]
    pub struct WgpuBindGroup0Entries<'a> {
        pub uniforms: wgpu::BindGroupEntry<'a>,
        pub entry_segments: wgpu::BindGroupEntry<'a>,
        pub stations: wgpu::BindGroupEntry<'a>,
    }
    impl<'a> WgpuBindGroup0Entries<'a> {
        pub fn new(params: WgpuBindGroup0EntriesParams<'a>) -> Self {
            Self {
                uniforms: wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer(params.uniforms),
                },
                entry_segments: wgpu::BindGroupEntry {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer(params.entry_segments),
                },
                stations: wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer(params.stations),
                },
            }
        }
        pub fn into_array(self) -> [wgpu::BindGroupEntry<'a>; 3] {
            [self.uniforms, self.entry_segments, self.stations]
        }
        pub fn collect<B: FromIterator<wgpu::BindGroupEntry<'a>>>(self) -> B {
            self.into_array().into_iter().collect()
        }
    }
    #[derive(Clone, Debug, Eq, Hash, Ord, PartialOrd, PartialEq)]
    pub struct WgpuBindGroup0(wgpu::BindGroup);
    impl WgpuBindGroup0 {
        pub const LAYOUT_DESCRIPTOR: wgpu::BindGroupLayoutDescriptor<'static> =
            wgpu::BindGroupLayoutDescriptor {
                label: Some("GpuTrip::BindGroup0::LayoutDescriptor"),
                entries: &[
                    #[doc = " @binding(0): \"uniforms\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: std::num::NonZeroU64::new(std::mem::size_of::<
                                _root::gpu_trip::Uniforms,
                            >(
                            )
                                as _),
                        },
                        count: None,
                    },
                    #[doc = " @binding(1): \"entry_segments\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    #[doc = " @binding(2): \"stations\""]
                    wgpu::BindGroupLayoutEntry {
                        binding: 2,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            };
        pub fn get_bind_group_layout(device: &wgpu::Device) -> wgpu::BindGroupLayout {
            device.create_bind_group_layout(&Self::LAYOUT_DESCRIPTOR)
        }
        pub fn from_bindings(device: &wgpu::Device, bindings: WgpuBindGroup0Entries) -> Self {
            let bind_group_layout = Self::get_bind_group_layout(device);
            let entries = bindings.into_array();
            let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("GpuTrip::BindGroup0"),
                layout: &bind_group_layout,
                entries: &entries,
            });
            Self(bind_group)
        }
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            pass.set_bind_group(0, &self.0, &[]);
        }
        pub fn inner(&self) -> &wgpu::BindGroup {
            &self.0
        }
        pub unsafe fn from_raw(bind_group: wgpu::BindGroup) -> Self {
            Self(bind_group)
        }
    }
    #[doc = " Bind groups can be set individually using their set(render_pass) method, or all at once using `WgpuBindGroups::set`."]
    #[doc = " For optimal performance with many draw calls, it's recommended to organize bindings into bind groups based on update frequency:"]
    #[doc = "   - Bind group 0: Least frequent updates (e.g. per frame resources)"]
    #[doc = "   - Bind group 1: More frequent updates"]
    #[doc = "   - Bind group 2: More frequent updates"]
    #[doc = "   - Bind group 3: Most frequent updates (e.g. per draw resources)"]
    #[derive(Debug, Copy, Clone)]
    pub struct WgpuBindGroups<'a> {
        pub bind_group0: &'a WgpuBindGroup0,
    }
    impl<'a> WgpuBindGroups<'a> {
        pub fn set(&self, pass: &mut impl SetBindGroup) {
            self.bind_group0.set(pass);
        }
    }
    #[derive(Debug)]
    pub struct WgpuPipelineLayout;
    impl WgpuPipelineLayout {
        pub fn bind_group_layout_entries(
            entries: [wgpu::BindGroupLayout; 1],
        ) -> [wgpu::BindGroupLayout; 1] {
            entries
        }
    }
    pub fn create_pipeline_layout(device: &wgpu::Device) -> wgpu::PipelineLayout {
        device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("GpuTrip::PipelineLayout"),
            bind_group_layouts: &[Some(&WgpuBindGroup0::get_bind_group_layout(device))],
            immediate_size: 0u32,
        })
    }
    pub fn create_shader_module_embed_source(device: &wgpu::Device) -> wgpu::ShaderModule {
        let source = std::borrow::Cow::Borrowed(SHADER_STRING);
        device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("gpu_trip.wgsl"),
            source: wgpu::ShaderSource::Wgsl(source),
        })
    }
    pub const SHADER_STRING: &str = r#"
struct Uniforms {
    screen_size: vec2<f32>,
    ticks_min: i32,
    canvas_length_min: f32,
    x_per_tick: f32,
    y_per_canvas_length: f32,
    pixels_per_point: f32,
}

struct Tick {
    value: i32,
}

struct CanvasLength {
    value: f32,
}

struct Style {
    thickness: f32,
    fill_rgba: u32,
}

struct EntrySegment {
    arr_seconds: i32,
    dep_seconds: i32,
    curr_index: u32,
    curr_progress: f32,
    connects_to_prev: u32,
    connects_to_next: u32,
    style: Style,
}

struct VertexOut {
    @location(0) color: vec4<f32>,
    @location(1) offset: f32,
    @location(2) half_width: f32,
    @builtin(position) position: vec4<f32>,
}

struct SegmentMeshVertex {
    along: f32,
    side: f32,
}

const TICKS_PER_SECOND: i32 = 100i;
const FEATHER_WIDTH_PX: f32 = 2f;
const SEGMENT_MESH_VERTICES: array<SegmentMeshVertex, 4> = array<SegmentMeshVertex, 4>(SegmentMeshVertex(0f, 1f), SegmentMeshVertex(0f, -1f), SegmentMeshVertex(1f, 1f), SegmentMeshVertex(1f, -1f));
const SEGMENT_MESH_INDICES: array<u32, 6> = array<u32, 6>(0u, 1u, 2u, 3u, 2u, 3u);
const SEGMENT_MESH_CONNECT_START: u32 = 4u;
const SEGMENT_MESH_LENGTH: u32 = 6u;

@group(0) @binding(0) 
var<uniform> uniforms: Uniforms;
@group(0) @binding(1) 
var<storage> entry_segments: array<EntrySegment>;
@group(0) @binding(2) 
var<storage> stations: array<CanvasLength>;

fn seconds_to_screen_x(secs: i32) -> f32 {
    let ticks = (secs * TICKS_PER_SECOND);
    let _e5 = uniforms.ticks_min;
    let _e10 = uniforms.x_per_tick;
    return (f32((ticks - _e5)) / _e10);
}

fn height_to_screen_y(height: CanvasLength) -> f32 {
    let _e4 = uniforms.canvas_length_min;
    let _e8 = uniforms.y_per_canvas_length;
    return ((height.value - _e4) / _e8);
}

fn entry_height(entry: EntrySegment) -> f32 {
    let _e4 = stations[entry.curr_index];
    let _e5 = height_to_screen_y(_e4);
    let _e11 = stations[(entry.curr_index + 1u)];
    let _e12 = height_to_screen_y(_e11);
    return mix(_e5, _e12, entry.curr_progress);
}

fn entry_arrival(entry_1: EntrySegment) -> vec2<f32> {
    let _e2 = seconds_to_screen_x(entry_1.arr_seconds);
    let _e3 = entry_height(entry_1);
    return vec2<f32>(_e2, _e3);
}

fn entry_departure(entry_2: EntrySegment) -> vec2<f32> {
    let _e2 = seconds_to_screen_x(entry_2.dep_seconds);
    let _e3 = entry_height(entry_2);
    return vec2<f32>(_e2, _e3);
}

fn normalize_or(v: vec2<f32>, fallback: vec2<f32>) -> vec2<f32> {
    let len = length(v);
    if (len < 0.00001f) {
        return fallback;
    }
    return (v / vec2(len));
}

fn outgoing_from_arrival(index: u32) -> vec2<f32> {
    let entry_3 = entry_segments[index];
    let _e4 = entry_arrival(entry_3);
    let _e5 = entry_departure(entry_3);
    if (entry_3.arr_seconds != entry_3.dep_seconds) {
        let _e13 = normalize_or((_e5 - _e4), vec2<f32>(1f, 0f));
        return _e13;
    }
    if (entry_3.connects_to_next != 0u) {
        let next = entry_segments[(index + 1u)];
        let _e22 = entry_arrival(next);
        let _e27 = normalize_or((_e22 - _e5), vec2<f32>(1f, 0f));
        return _e27;
    }
    return vec2<f32>(1f, 0f);
}

fn line_feather(pixels_per_point: f32) -> f32 {
    return (FEATHER_WIDTH_PX / max(pixels_per_point, 0.000001f));
}

fn left_normal(dir: vec2<f32>) -> vec2<f32> {
    return vec2<f32>(-(dir.y), dir.x);
}

fn joint_vertex(p: vec2<f32>, dir_in_1: vec2<f32>, dir_out_1: vec2<f32>, side: f32, half_width: f32) -> vec2<f32> {
    let _e1 = left_normal(dir_in_1);
    let n_in = (_e1 * side);
    let _e5 = left_normal(dir_out_1);
    let n_out = (_e5 * side);
    let denom = max((1f + dot(dir_in_1, dir_out_1)), 0.25f);
    return (p + ((half_width * (n_in + n_out)) / vec2(denom)));
}

fn line_alpha(offset: f32, half_width_1: f32, feather: f32) -> f32 {
    return (1f - smoothstep((half_width_1 - (feather * 0.5f)), (half_width_1 + (feather * 0.5f)), abs(offset)));
}

fn segment_quad_pos(p0_: vec2<f32>, p1_: vec2<f32>, corner: vec2<f32>, half_extent: f32) -> vec2<f32> {
    let _e6 = normalize_or((p1_ - p0_), vec2<f32>(1f, 0f));
    let _e7 = left_normal(_e6);
    let center = ((p0_ + p1_) * 0.5f);
    let half_len = (length((p1_ - p0_)) * 0.5f);
    return ((center + (_e6 * (corner.x * half_len))) + (_e7 * (corner.y * half_extent)));
}

@vertex 
fn vs_main(@builtin(vertex_index) vertex_index: u32, @builtin(instance_index) instance_index: u32) -> VertexOut {
    var p_connect: vec2<f32>;
    var dir_connect: vec2<f32>;
    var dir_outgoing: vec2<f32>;
    var dir_arr_in: vec2<f32>;
    var local: bool;
    var joint_p: vec2<f32>;
    var dir_in: vec2<f32>;
    var dir_out: vec2<f32>;
    var local_1: bool;

    let entry_4 = entry_segments[instance_index];
    let half_width_2 = (entry_4.style.thickness * 0.5f);
    let _e10 = uniforms.pixels_per_point;
    let _e11 = line_feather(_e10);
    let mesh = SEGMENT_MESH_VERTICES[SEGMENT_MESH_INDICES[vertex_index]];
    let is_end = (mesh.along > 0.5f);
    let is_connect = (vertex_index >= SEGMENT_MESH_CONNECT_START);
    let _e22 = entry_arrival(entry_4);
    let _e23 = entry_departure(entry_4);
    let is_dwell = (entry_4.arr_seconds != entry_4.dep_seconds);
    let _e31 = normalize_or((_e23 - _e22), vec2<f32>(1f, 0f));
    p_connect = _e23;
    dir_connect = _e31;
    dir_outgoing = _e31;
    if (entry_4.connects_to_next != 0u) {
        let next_1 = entry_segments[(instance_index + 1u)];
        let _e43 = entry_arrival(next_1);
        p_connect = _e43;
        let _e44 = p_connect;
        let _e46 = normalize_or((_e44 - _e23), _e31);
        dir_connect = _e46;
        let _e49 = outgoing_from_arrival((instance_index + 1u));
        dir_outgoing = _e49;
    }
    dir_arr_in = _e31;
    if (entry_4.connects_to_prev != 0u) {
        local = (instance_index > 0u);
    } else {
        local = false;
    }
    let _e59 = local;
    if _e59 {
        let prev = entry_segments[(instance_index - 1u)];
        let _e65 = entry_departure(prev);
        let _e67 = normalize_or((_e22 - _e65), _e31);
        dir_arr_in = _e67;
    } else {
        if !(is_dwell) {
            let _e69 = dir_connect;
            dir_arr_in = _e69;
        }
    }
    let _e70 = dir_connect;
    let dir_arr_out = select(_e31, _e70, !(is_dwell));
    let _e73 = dir_arr_in;
    let dir_dep_in = select(_e31, _e73, !(is_dwell));
    joint_p = _e22;
    let _e77 = dir_arr_in;
    dir_in = _e77;
    dir_out = dir_arr_out;
    if is_connect {
        local_1 = is_end;
    } else {
        local_1 = false;
    }
    let _e83 = local_1;
    if _e83 {
        let _e84 = p_connect;
        joint_p = _e84;
        let _e85 = dir_connect;
        dir_in = _e85;
        let _e86 = dir_outgoing;
        dir_out = _e86;
    } else {
        if is_end {
            joint_p = _e23;
            dir_in = dir_dep_in;
            let _e87 = dir_connect;
            dir_out = _e87;
        }
    }
    let offset_1 = (mesh.side * (half_width_2 + (_e11 * 0.5f)));
    let _e93 = joint_p;
    let _e94 = dir_in;
    let _e95 = dir_out;
    let _e100 = joint_vertex(_e93, _e94, _e95, mesh.side, (half_width_2 + (_e11 * 0.5f)));
    let _e105 = uniforms.screen_size.x;
    let clip_x = (((_e100.x / _e105) * 2f) - 1f);
    let _e115 = uniforms.screen_size.y;
    let clip_y = (1f - ((_e100.y / _e115) * 2f));
    let rgba = entry_4.style.fill_rgba;
    let color = vec4<f32>((f32(((rgba >> 24u) & 255u)) / 255f), (f32(((rgba >> 16u) & 255u)) / 255f), (f32(((rgba >> 8u) & 255u)) / 255f), (f32((rgba & 255u)) / 255f));
    return VertexOut(color, offset_1, half_width_2, vec4<f32>(clip_x, clip_y, 0f, 1f));
}

@fragment 
fn fs_main(in: VertexOut) -> @location(0) vec4<f32> {
    let _e2 = uniforms.pixels_per_point;
    let _e3 = line_feather(_e2);
    let _e7 = line_alpha(in.offset, in.half_width, _e3);
    return vec4<f32>(in.color.xyz, (in.color.w * _e7));
}
"#;
}
#[allow(unused, non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod bytemuck_impls {
    use super::_root;
    use super::_root::*;
    unsafe impl bytemuck::Zeroable for gpu_trip::Uniforms {}
    unsafe impl bytemuck::Pod for gpu_trip::Uniforms {}
    unsafe impl bytemuck::Zeroable for gpu_trip::CanvasLength {}
    unsafe impl bytemuck::Pod for gpu_trip::CanvasLength {}
    unsafe impl bytemuck::Zeroable for gpu_trip::Style {}
    unsafe impl bytemuck::Pod for gpu_trip::Style {}
    unsafe impl bytemuck::Zeroable for gpu_trip::EntrySegment {}
    unsafe impl bytemuck::Pod for gpu_trip::EntrySegment {}
}
