name: Build WASM

on:
  push:
    paths:
      - "wasm/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "wasm/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build WASM release
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-release
          path: ./wasm/target/wasm32-unknown-unknown/release/*.wasm
