name: Build Main

on:
  push:
    branches:
      - main
    paths:
      - 'web/main/**'
      - '.github/workflows/main.yml'
  workflow_dispatch:

concurrency:
  group: main
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          lfs: true

      - uses: extractions/setup-just@v3

      - name: Prepare Main
        run: just prep-main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: WenSimEHRP/Paiagram-Archive
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          publish_branch: main
          publish_dir: ./dist/main
          destination_dir: main
