name: Nightly Build & Pages Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.*'
      - 'flake.*'
      - 'crates/**'
      - '.cargo/**'
      - 'web/nightly/**'
      - '.github/workflows/nightly.yml'
  workflow_dispatch:

concurrency:
  group: wasm
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: Swatinem/rust-cache@v2

      - name: Download Sarasa fonts
        run: nix develop .#default --command just get-fonts

      - name: Prepare Pages artifact
        run: nix develop .#default --command just prep-wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: wasm-pages
          path: ./dist/nightly

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: WenSimEHRP/Paiagram-Archive
          publish_branch: main
          publish_dir: ./dist/nightly
          destination_dir: nightly
